### ISSUE TITLE
Code Release for Chapter 13

### ISSUE THREAD

**Issue by Sohom1997** [deep-learning-with-pytorch/dlwpt-code#1]
The MEAP version of the book already includes Chapter 13 on Image Segmentation. When will the corresponding code for Chapter 13 be released? @elistevens looking forward to the full code release for a more fruitful reading of the book.

**Comment by elistevens** [comment]
I've just pushed up the most recent version of the code. It includes code for the entire book. In the current version of the book (not yet available publicly), we've split chapter 13 into two parts, so all of the `diagnose.py` discussion is now in chapter 14.

This contains some preliminary updates for PyTorch v1.3.0, but I think there's going to be some more work we'll need to clean things up.

Please let us know if there are additional issues!
