### ISSUE TITLE
'Ct' object has no attribute 'build3dLungMask'?

### ISSUE THREAD

**Issue by mangozy** [deep-learning-with-pytorch/dlwpt-code#10]
In both "p2ch10_explore_data.ipynb" and "p2ch10/dsets.py", I am not able to find 'build3dLungMask'.

`from p2ch10.dsets import getCt`
`ct = getCt(series_uid)`
`air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask = ct.build3dLungMask()`

`---------------------------------------------------------------------------`
`AttributeError                            Traceback (most recent call last)`
`<ipython-input-23-2630724d96f5> in <module>`
`      1 from p2ch10.dsets import getCt`
`      2 ct = getCt(series_uid)`
`----> 3 air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask = ct.build3dLungMask()`
`AttributeError: 'Ct' object has no attribute 'build3dLungMask'`

![build3dlungmask](https://user-images.githubusercontent.com/32133971/88472349-be107580-cedf-11ea-9e8f-1708d442103d.png)

**Comment by elistevens** [comment]
Ah, yes, those cells are old experiments with getting 3D renderings of CT scans, and used some masking code that was previously present, but was eventually removed due to not being strictly needed. If you drop this into a cell above that, you'll get the functions pretty much as originally defined:

```python
import scipy.ndimage.morphology
def build2dLungMask(ct, mask_ndx, threshold_gcc = 0.7):
    dense_mask = ct.hu_a[mask_ndx] > threshold_gcc
    denoise_mask = scipy.ndimage.morphology.binary_closing(dense_mask, iterations=2)
    tissue_mask = scipy.ndimage.morphology.binary_opening(denoise_mask, iterations=10)
    body_mask = scipy.ndimage.morphology.binary_fill_holes(tissue_mask)
    air_mask = scipy.ndimage.morphology.binary_fill_holes(body_mask & ~tissue_mask)

    lung_mask = scipy.ndimage.morphology.binary_dilation(air_mask, iterations=2)

    return air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask


def build3dLungMask(ct):
    air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask = mask_list = \
        [np.zeros_like(ct.hu_a, dtype=np.bool) for _ in range(6)]

    for mask_ndx in range(ct.hu_a.shape[0]):
        for i, mask_ary in enumerate(build2dLungMask(ct, mask_ndx)):
            mask_list[i][mask_ndx] = mask_ary

    return air_mask, lung_mask, dense_mask, denoise_mask, tissue_mask, body_mask
```
You'll have to change the call site to be `build3dLungMask(ct)`.

I'll push an update to the repo here shortly. Be aware that this particular experiment was a _failed_ experiment; the resulting visualization doesn't look very good (which is why it was abandoned)!

**Comment by mangozy** [comment]
Thank you so much for the prompt reply! It is working now. I am working on my own project that's related to yours. Perhaps, I might need to do more experiments to make this visualization to work. Once I have the code to work, I will let you know. Thanks again.
