### ISSUE TITLE
Typo in your PDF copy of Chapter 10?

### ISSUE THREAD

**Issue by mangozy** [deep-learning-with-pytorch/dlwpt-code#13]
In chapter 10 on page 258, the Bash shell code explanation says `Counts the number of lines that end with 1, which indicates malignancy`, but in fact, lines end with 1 doesn't mean malignancy. It means it's a nodule and it can be malignant or benign.

In the later section, you also have `0 for a candidate that is not an actual nodule, and 1 for a candidate that is a nodule, either malignant or benign`. This is kind of confusing.

![ch10 typo](https://user-images.githubusercontent.com/32133971/88584720-1484cd80-d020-11ea-82dd-c1cb2a4dbfc4.png)

**Comment by elistevens** [comment]
Yes, you're right, thanks for catching the error. I'll update the errata document to include this.
