### ISSUE TITLE
requirements.txt referenced but unavailable

### ISSUE THREAD

**Issue by charlesfrye** [deep-learning-with-pytorch/dlwpt-code#14]
Thanks for making a really excellent book! Excited to dive in.

On pages xxv and 14 ([Section 1.5](https://livebook.manning.com/book/deep-learning-with-pytorch/chapter-1/point-8518-78-78-0)), there's mention of a `requirements.txt` file being provided for use with `pip` to ensure that all packages are the correct version.

I've looked around and been unable to find this file, either within this repo or on the internet. Where/Is it available?

**Comment by elistevens** [comment]
Sorry about that! I've added the file now.
