### ISSUE TITLE
Kernel keeps crashing at the exact same point while training during the 2nd epoch (p2ch12.training.LunaTrainingApp)

### ISSUE THREAD

**Issue by navpreetnp7** [deep-learning-with-pytorch/dlwpt-code#17]
I am trying to train the luna model using data augmentation of chapter 12. The issue I am facing that the kernel crashes everytime during the end of the 2nd epoch of training set. The same behaviour is exhibited whether I run from Jupyter notebook or command line. If I check my resources during training ( attached ), it doesn't look like there is any memory shortage in ram or gpu.

![Screenshot (2)](https://user-images.githubusercontent.com/13185738/90909031-d39b9100-e3f2-11ea-9525-c756d3a0cf08.png)

And here's the logs while training.

![Screenshot (3)](https://user-images.githubusercontent.com/13185738/90909812-f8443880-e3f3-11ea-9d26-feccc3ef2029.png)

![Screenshot (4)](https://user-images.githubusercontent.com/13185738/90909330-37be5500-e3f3-11ea-8254-04cb0fd9886a.png)

After this the training crashes. Can you please point out what seems to be the issue? I am running the exact same code except change in the path for the subset data that I downloaded in my local machine.
I am running Windows 10, 32 GB RAM, 8 GB GPU.
I also tried with num-workers = 4,6 with the same result (only slower), decreased the batch size to 64 and again same thing.
Also during the 2nd epoch, my systems seems to slow down as i experience some lag in switching tabs/windows but if i check the task manager as in screenshot, there is plenty of ram left.

Any help would be appreciated as I am new to deep learning and I am running a huge model for the first time. Thank you.

**Comment by melhzy** [comment]
Error keeps happening to my machine.

**Comment by MuhammedIkbalKARADELI** [comment]
I have same issues for different process. Did you solve your problem? If you solved this problem, could you help me about kernel crashes?
