### ISSUE TITLE
ImportError: cannot import name 'BytesType' from 'diskcache.core'

### ISSUE THREAD

**Issue by sandip1604** [deep-learning-with-pytorch/dlwpt-code#19]
Hello Everyone

I am trying to learn along with the book by building cancer detection along with the book. However I get the following error. 
Traceback (most recent call last):

  File "/home/sandip/code/dsets.py", line 16, in <module>
    from util.disk import getCache

  File "/home/sandip/code/util/disk.py", line 4, in <module>
    from diskcache.core import BytesType, MODE_BINARY, BytesIO

ImportError: cannot import name 'BytesType' from 'diskcache.core' (/home/sandip/anaconda3/envs/breast_cancer/lib/python3.7/site-packages/diskcache/core.py)

![image](https://user-images.githubusercontent.com/60662785/91618391-3b545d80-e958-11ea-8562-6502a7aa6e23.png)

Please guide me to fix the issue. 

Thanks in advance

**Comment by emilearthur** [comment]
same issue here!!

**Comment by emilearthur** [comment]
install diskcache version 4.1.0., Current version of diskcache does not have BytesType included. 
Use pip install "diskcache==4.1.0" instead of pip install diskcache, which installs the current version
