### ISSUE TITLE
Possible error on fig 6.6

### ISSUE THREAD

**Issue by Pearcekieser** [deep-learning-with-pytorch/dlwpt-code#29]
Subgraph titled "D: TANH(-3*x - 1.5)" plot shows d= tanh(-3x + 1.5).  C + D graph also indicates that D is tanh(-3x + 1.5). Pg 150

**Comment by hopezh** [comment]
Yes, I just noticed this error, too. 

https://github.com/deep-learning-with-pytorch/dlwpt-code/issues/52#issue-792723830
