### ISSUE TITLE
Memory Errors During Preping Cache

### ISSUE THREAD

**Issue by amrosado** [deep-learning-with-pytorch/dlwpt-code#3]
I can't seem to get the provided code to work for the entire luna dataset and keep running into memory errors thrown by the SimpleITK package.  After looking at the code for some time, I tried manipulating the code to free up more memory when things weren't needed, etc., but I can't get the cache preping code to work for the complete dataset (only 0-3 subsets together work).  It seems as the cache preping code continue to accumulate more and more memory without writing much to my hard disk.  I believe it might be because the diskcache isn't working like expected whereby writing steps for the FanoutCache are timing out even when set at 1s.  Moreover, the specified shard number (64) implies concurrent writing that isn't shaped by worker number.  Could you explain the selected FanoutCache configuration?  What changes could potentially mitigate memory problems during the prepcache step if we were attempting to run the complete dataset?

**Comment by elistevens** [comment]
Hi, sorry about the slow reply. Only digging myself out from the holidays now. 

Can you please let me know what the hardware and operating system of the machine that you're running the code on is, and exactly what commands you're running? Making a gist with the output of the commands would also be helpful.

The 64 shards was somewhat arbitrarily chosen, with the idea to allow 8x worker processes to be able to write mostly without having contention for write locks.

**Comment by amrosado** [comment]
Thanks so much for your reply.  I'm using a Windows 10 machine (10.0.18363 Build 18363) with a i7-8750H CPU @ 2.20Ghz, 16 GB RAM, and Nvidia RTX 2060 with 6GB RAM.

 I've tried running the prepcache script with between 2-6 workers and batch_size 128-1024.  I've also modified your code a bit to try to free up additional RAM by deleting variables.  I've also tried using different versions of SimpleITK because I thought there might be a memory leak with it.  I don't remember the different versions, etc. I've tried.  I also thought it could be a possible limitation with my ability to write to disk.  I've bought a new hard drive, but haven't tested the code yet with that hard drive.

If I run the script multiple times where it runs out of memory it will eventually reach a state where it can go through all the data.  If I start the prepcache script from a state with no existing cache saved on my disk it will give me an memory error.

**Comment by amrosado** [comment]
I would like to follow up to this issue that was recently closed and state that @elistevens suggestion to try to execute the script more than once on the same set of data works because some computations in the set do get cached and eventually enough results get cached to overcome my issue.  I wasn't able to identify a specific data set that caused my issue.  This problem seems to be Windows specific.

**Comment by elistevens** [comment]
Thanks for following up. Sorry we haven't been able to pinpoint the issue.

I was able to create the dataset on windows without problems. That said,
I've got 32GB of RAM in this system, so maybe that's enough to make a
difference?  Still, I'd think that running with fewer workers should solve
the problem.
