### ISSUE TITLE
Issue in the book

### ISSUE THREAD

**Issue by theonlyNischal** [deep-learning-with-pytorch/dlwpt-code#33]
![image](https://user-images.githubusercontent.com/23012980/99825774-94124b80-2b7f-11eb-89ca-c3a8e7fe514f.png)

Page 272, In listing 10.12, should the mysterious  **1((CO10-1))** be there?
I have checked the code implementation at https://github.com/deep-learning-with-pytorch/dlwpt-code/blob/323de27e517c279ae69318d9ea0a7e6f416701ba/p2ch10/dsets.py#L200 and that thing is not there.

Also, Is this the right place to raise an issue about the book too?

**Comment by t-vi** [comment]
This is an artifact of a code annotation (a "callout") gone wrong, and they shouldn't be there. Thank you for reporting!

If you got the book from manning, there also is an errata thread in LiveBook (linked from the publicly available [errata page](https://manning-content.s3.amazonaws.com/download/0/a6cd1b7-9c2c-4f50-9b4a-25769e252afe/Stevens_DeepLearningwithPytorch_err.html)).

Best regards

Thomas

**Comment by theonlyNischal** [comment]
Thank you so much!!
