### ISSUE TITLE
Missing train_seg.py and train_cls.py

### ISSUE THREAD

**Issue by jeffj9930** [deep-learning-with-pytorch/dlwpt-code#34]
Hi,
I can't run items in chapter 13 because at least 2 files are missing: train_cls.py and train_seg.py. I see these in the LiveBook. Am I  supposed to edit the files from Git or Manning to match these? I don't understand. The line numbers don't match so I think there is a store of working code that I don't see on Git or Manning. 
I have been making continual edits to code and CSV files.
Is there an easier way? Is it a work-in-progress and I should wait a while longer?
Jeff

**Comment by t-vi** [comment]
Hi Jeff,

this isn't ideal, but so the code is all there but got rearranged at the last minute. In chapter 12 and 14 we only have classification and in chapter 13 we only have segmentation, and the files are training.py in either case. Sorry for the confusion!

Best regards

Thomas

**Comment by elistevens** [comment]
I've updated the code for the repo, and will push it up shortly.
