### ISSUE TITLE
where to place data?

### ISSUE THREAD

**Issue by rosagradilla19** [deep-learning-with-pytorch/dlwpt-code#35]
Where am I supposed to put the data files? 
would the path be data/subset*/*.mhd or data-unversioned/subsets/subset*/*.mhd

I don't understand what the puporse of data-unversioned is? When I run the training scripts in ch11 and ch12 data-unversioned is created and inside there's a cache folder

**Comment by t-vi** [comment]
The idea is that data is in git and the large dataset is in data-unversioned, so versioned here is "in version control".
