### ISSUE TITLE
p2ch09?!

### ISSUE THREAD

**Issue by naexyz** [deep-learning-with-pytorch/dlwpt-code#5]
It looks like this one is missing.
;o)

**Comment by elistevens** [comment]
Hi!

Since chapter 9 is only covering the part 2 project at a high level, there's no code for chapter 9. Perhaps we should have a directory with just a README that says as much?

Hope you're liking the book!

**Comment by naexyz** [comment]
Perhaps a README will be a good idea ;-)

A better one however might be a comment about a new code version!?
Me, I’m running the old one (see attached).

… and I do like the book ;o)
