### ISSUE TITLE
Where to find the latest checkpoints?

### ISSUE THREAD

**Issue by andreeabir** [deep-learning-with-pytorch/dlwpt-code#7]
Hi,

I tried to test the p2ch14.nodule_analysis module, but I did not found the checkpoints: data/part2/models/cls_2020-02-06_14.16.55_final-nodule-nonnodule.best.state, data/part2/models/seg_2020-01-26_19.45.12_w4d3c1-bal_1_nodupe-label_pos-d1_fn8-adam.best.state. Will these models be available? Thanks!

**Comment by elistevens** [comment]
Thank you for bringing this to our attention! I've just pushed a commit that updates the repo to include the files. Please let us know if everything's working for you now. Cheers!

**Comment by andreeabir** [comment]
Thank you! Everything is working now.
