### ISSUE TITLE
Part 3 Chapter 15 request_batching_server.py

### ISSUE THREAD

**Issue by Vedant-R** [deep-learning-with-pytorch/dlwpt-code#85]
Hi,

This is an exceptional solution provided for async deployment and model serving.

I wanted to enquire if there are examples of unit tests for this. I have been continuously struggling with unit tests for sanic async post method with the following error:

```
async with self.queue_lock:
AttributeError: __aenter__
```

I am getting this error for the line:
```
58 async with self.queue_lock:
59        if len(self.queue) >= MAX_QUEUE_SIZE:
```

The test I am trying:
```
import json
import pytest
from ..app import app

@pytest.mark.asyncio
async def test_basic_post():
    _, response = await app.asgi_client.post("/predict", data=json.dumps(INPUT), headers=HEADERS)
    print(response)
```

Please do let me know if anyone has come across this and have a solution.

**Comment by Vedant-R** [comment]
Got this done, thank you. Closing it

**Comment by AlexBlack2202** [comment]
> Got this done, thank you. Closing it

hello, i have same issuse as your, can you show me how to fix this
